import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

type Batch = {
  id: string; pharmacy_name: string; pharmacy_address: string | null; pharmacy_abn: string | null;
  period_start: string; period_end: string; total_cases: number;
  total_amount_ex_gst: number; total_gst: number; total_amount: number;
  generated_by: string | null; created_at: string;
};

type Program = { id: string; code: string; name: string; standard_fee_ex_gst: number; gst_rate: number };

type Case = {
  id: string; encounter_reference: string; patient_initials: string | null;
  patient_age: number | null; patient_sex: string | null; condition_name: string;
  consult_date: string; status: string; hard_fail_count: number; warn_count: number;
  fee_ex_gst: number; gst_amount: number; total_amount: number;
  protocol_completed: boolean; red_flags_negative: boolean;
  within_age_range: boolean; within_onset_window: boolean | null; notes: string | null;
};

function ageband(age: number | null): string {
  if (!age) return '—';
  if (age < 18) return '<18';
  if (age <= 25) return '18–25';
  if (age <= 40) return '26–40';
  if (age <= 55) return '41–55';
  if (age <= 65) return '56–65';
  return '>65';
}

export function generateClaimPDF(batch: Batch, program: Program, cases: Case[]) {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();

  // Header
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Community Pharmacist Program – Claim Summary', 14, 18);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  let y = 26;

  // Pharmacy details
  doc.setFont('helvetica', 'bold');
  doc.text('Pharmacy:', 14, y);
  doc.setFont('helvetica', 'normal');
  doc.text(batch.pharmacy_name, 45, y);
  if (batch.pharmacy_abn) { y += 5; doc.text(`ABN: ${batch.pharmacy_abn}`, 45, y); }
  if (batch.pharmacy_address) { y += 5; doc.text(batch.pharmacy_address, 45, y); }

  // Program & batch details
  y += 8;
  doc.setFont('helvetica', 'bold');
  doc.text('Program:', 14, y);
  doc.setFont('helvetica', 'normal');
  doc.text(program.name, 45, y);

  y += 5;
  doc.text(`Claim Period: ${batch.period_start} – ${batch.period_end}`, 14, y);
  y += 5;
  doc.text(`Batch ID: ${batch.id.slice(0, 8)}`, 14, y);
  doc.text(`Date Generated: ${new Date().toLocaleDateString('en-AU')}`, 120, y);
  if (batch.generated_by) doc.text(`Generated By: ${batch.generated_by}`, 200, y);

  // Totals
  y += 8;
  doc.setFont('helvetica', 'bold');
  doc.text('Summary', 14, y);
  doc.setFont('helvetica', 'normal');
  y += 5;
  doc.text(`Total Cases: ${batch.total_cases}`, 14, y);
  doc.text(`Fee/Case (ex GST): $${Number(program.standard_fee_ex_gst).toFixed(2)}`, 70, y);
  doc.text(`Total ex GST: $${Number(batch.total_amount_ex_gst).toFixed(2)}`, 140, y);
  doc.text(`GST: $${Number(batch.total_gst).toFixed(2)}`, 200, y);
  doc.setFont('helvetica', 'bold');
  doc.text(`Grand Total (inc GST): $${Number(batch.total_amount).toFixed(2)}`, 230, y);

  // Detail table
  y += 8;
  const tableData = cases.map((c, i) => [
    String(i + 1),
    c.encounter_reference,
    c.consult_date,
    c.condition_name,
    `${c.patient_initials || '—'} (${ageband(c.patient_age)})`,
    c.patient_sex || '—',
    c.protocol_completed ? 'Y' : 'N',
    c.red_flags_negative ? 'Y' : 'N',
    c.within_age_range ? 'Y' : 'N',
    c.within_onset_window === null ? 'N/A' : c.within_onset_window ? 'Y' : 'N',
    String(c.hard_fail_count),
    String(c.warn_count),
    `$${Number(c.fee_ex_gst).toFixed(2)}`,
    `$${Number(c.gst_amount).toFixed(2)}`,
    `$${Number(c.total_amount).toFixed(2)}`,
  ]);

  autoTable(doc, {
    startY: y,
    head: [['#', 'Ref', 'Date', 'Condition', 'Patient', 'Sex', 'Proto', 'RF−', 'Age✓', 'Onset✓', 'Fails', 'Warns', 'Ex GST', 'GST', 'Total']],
    body: tableData,
    styles: { fontSize: 7, cellPadding: 1.5 },
    headStyles: { fillColor: [25, 75, 80], fontSize: 7 },
    alternateRowStyles: { fillColor: [245, 248, 250] },
    margin: { left: 14, right: 14 },
  });

  // Footer
  const finalY = (doc as any).lastAutoTable?.finalY || y + 50;
  doc.setFontSize(7);
  doc.setFont('helvetica', 'italic');
  doc.text('Generated by ChemistCare PrescriberOS – Claim Validation Engine. For reconciliation purposes only.', 14, finalY + 8);

  doc.save(`Claim_Summary_${program.code}_${batch.period_start}_${batch.period_end}.pdf`);
}
